crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('product/', ProductsListAddView.as_view(), name='products_add'),
    # path('products-add/', ProductCreateAndListView.as_view(), name='products_create_view'),
    path('products-add/', ProductCreateAndListView.as_view(), name='products_combined_view'),
    path('employs/', EmploysCreateAndListView.as_view(), name='employ_list'),
    path('employs/delete/<int:pk>', EmployDeleteView.as_view(), name='employ_delete')
]

crm_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crm/', include('crm.urls')),
]

crm/models.py
from django.db import models
from django.core import validators


class Employ(models.Model):
    name = models.CharField(max_length=32)
    email = models.EmailField(max_length=254)
    status = models.BooleanField(default=True)

    class Meta:
        db_table = "employ"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        db_table = "product"

    def __str__(self):
        return self.name


class PaymentMethods(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        db_table = "payment_method"

    def __str__(self):
        return self.name


class Operations(models.Model):
    fk_name_of_product = models.ForeignKey(Products, on_delete=models.PROTECT, null=True)
    deb_cred = models.BooleanField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.IntegerField(validators=[validators.MinValueValidator(0)])

    class Meta:
        db_table = "operation"

    def __str__(self):
        return f"{self.fk_name_of_product} - {self.price}"


class Check(models.Model):
    sell_id = models.IntegerField(validators=[validators.MinValueValidator(0)])
    date = models.DateTimeField(auto_now_add=True)
    fk_stuff = models.ForeignKey(Employ, on_delete=models.PROTECT, null=True)
    total = models.DecimalField(max_digits=15, decimal_places=2, validators=[validators.MinValueValidator(0)])
    fk_payment = models.ForeignKey(PaymentMethods, on_delete=models.PROTECT, null=True)
    notice = models.TextField(null=True)

    class Meta:
        db_table = "check"

    def __str__(self):
        return f"Check ID: {self.sell_id}"

crm/forms.py
from django import forms
from .models import *


class ProductForm(forms.ModelForm):
    name = forms.CharField(label="Имя")

    class Meta:
        model = Products
        fields = ['name']


class EmployForm(forms.ModelForm):

    class Meta:
        model = Employ
        fields = "__all__"

crm/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.views import View
from django.views.generic import ListView, FormView
from django.views.generic.edit import CreateView, DeleteView
from .models import *
from .forms import *
from django.urls import reverse_lazy


class ProductsListAddView(FormView, ListView):
    model = Products  # which table use for create this list
    template_name = 'crm/products_add_list.html'
    context_object_name = 'products_add'  # how it will be name in template
    form_class = ProductForm  # get form from
    success_url = reverse_lazy('crm:products_add')  # redirect to URL path name "products" from "crm" namespace
    paginate_by = 5  # how many items per page

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)


class ProductCreateAndListView(CreateView, ListView):
    model = Products
    template_name = 'crm/products_combined.html'
    form_class = ProductForm
    context_object_name = 'product_list'
    success_url = reverse_lazy('crm:products_combined_view')

    def post(self, request, *args, **kwargs):
        # self.object_list = self.get_queryset()
        if 'delete_selected' in request.POST:
            selected_items = request.POST.getlist('selected_item')
            Products.objects.filter(id__in=selected_items).delete()
            return redirect(self.request.path_info)
        elif "save_item" in request.POST:
            form = self.get_form()
            return self.form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Products'
        # print(context)
        return context


class EmploysCreateAndListView(View):
    model = Employ
    template_name = 'crm/employs.html'
    form_class = ProductForm
    context_object_name = 'employs'
    success_url = reverse_lazy('crm:employ_list')

    def get(self, request, *args, **kwargs):
        form = EmployForm()
        employs = Employ.objects.all()
        return render(request, self.template_name, {'form': form, 'employs': employs})

    def post(self, request, *args, **kwargs):
        form = EmployForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crm:employ_list')


class EmployDeleteView(DeleteView):
    model = Employ
    template_name = 'crm/employ_confirm_delete.html'
    success_url = reverse_lazy('crm:employ_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

crm/templates/crm/employ_confirm_delete.html
{% extends 'crm/main.html' %}

{% block title %}{{title}}{% endblock %}

{% block  content %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-header">
        <h3 class="text-center">Delete Employ</h3>
      </div>
      <div class="card-body">
        <p class="text-center">Are you sure you want to delete the employ "{{ object.name }}"?</p>
        <form method="POST">
        {% csrf_token %}
          <div class="form-group row">
            <div class="col-sm-12 text-center">
              <input type="submit" class="btn btn-danger" value="Confirm">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

crm/templates/crm/employs.html
{% extends 'crm/main.html' %}
{% load crispy_forms_tags %}

{% block title %}{{title}}{% endblock %}

{% block  content %}
<div class="row">
    <div class="col-md-6">
        <h2>Add Employ</h2>
        <form method="post">
            {% csrf_token %}
                {{ form }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
   <div class="col-md-6">
    <h2>Employ List</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for employ in employs %}
            <tr>
                <td>{{ employ.id }}</td>
                <td>{{ employ.name }}</td>
                <td>{{ employ.email }}</td>
                <td>
                    <input type="checkbox" {{ employ.status|yesno:"checked," }} disabled>
                </td>
                <td>
                    <a href="{% url 'crm:employ_delete' employ.id %}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5">No employs yet.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% endblock content %}

crm/templates/crm/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CRM{% endblock %}</title>
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">-->
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
    <div class="container mt-5">
        {% block content %} {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

crm/templates/crm/products_add_list.html
{% extends 'crm/main.html' %}
{% block content %}

    <table class="table">

        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя операции</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products_add %}
        <tr>
            <th scope="row">{{product.id}}</th>
            <td>{{product.name}}</td>
<!--            <td><input type="checkbox" name="selected_item" value="{{product.id}}"></td>-->
        </tr>
        {% endfor %}
        </tbody>
    </table>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Product</button>
  </form>
{% endblock content %}

crm/templates/crm/products_combined.html
{% extends 'crm/main.html' %}

{% block title %}{{title}}{% endblock %}

{% block  content %}
<h1>Products</h1>

<form method="post">
{% csrf_token %}
    <table class="table">

        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя операции</th>
            <th scope="col">Удалить</th>
        </tr>
        </thead>
        <tbody>
        {% for product in object_list %}
        <tr>
            <th scope="row">{{product.id}}</th>
            <td>{{product.name}}</td>
            <td><input type="checkbox" name="selected_item" value="{{product.id}}"></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <button  type="submit" name="delete_selected">Удалить</button>
</form>
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button  type="submit" name="save_item">Сохранить</button>
</form>

{% endblock content %}

crm/templates/crm/products_create.html
{% extends "crm/main.html" %}

{% block  content %}
<h1>Products</h1>

<form method="post">
{% csrf_token %}
    <table class="table">

        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя операции</th>
        </tr>
        </thead>
        <tbody>
        {% for product in product_list_create %}
        <tr>
            <th scope="row">{{product.id}}</th>
            <td>{{product.name}}</td>
            <td><input type="checkbox" name="selected_item" value="{{product.id}}"></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <button  type="submit">Удалить</button>
</form>
<br>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
<!--            <input type="submit" value="Save">-->
    <button  type="submit">Сохранить</button>
</form>

{% endblock content %}